{
 "title": "# Enhanced Envoy Clusters Dashboard",
 "description": "Enhanced dashboard showing Envoy Clusters with comprehensive metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "clusterNameLabel", "query": "cluster_name" },
   {
    "name": "Namespace",
    "query": "label_values(envoy_cluster_upstream_rq_total,namespace)"
   },
   {
    "name": "app",
    "query": {
     "query": "query_result(sum({namespace=\"$Namespace\",__name__=\"envoy_server_version\"}) by (pod))"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "query_result(sum({namespace=\"$Namespace\",__name__=\"envoy_server_version\", pod=~\"$app-.*\"}) by (pod))"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "query_result(sum({namespace=\"$Namespace\",__name__=\"envoy_cluster_upstream_rq_total\", pod=~\"$app-.*\"}) by ($clusterNameLabel))"
    }
   },
   {
    "name": "http_conn_manager_prefix",
    "query": "label_values(envoy_http_downstream_cx_total{namespace=\"$Namespace\",pod=~\"$pod\"},http_conn_manager_prefix)"
   },
   { "name": "quantiles", "query": "0.9" }
  ]
 },
 "panels": [
  { "title": "Server Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_uptime{namespace=~\"$Namespace\",pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}\n"
    }
   ]
  },
  {
   "title": "Server Live",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_live{namespace=~\"$Namespace\",pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}\n"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_cx_total{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Memory Allocated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_allocated{namespace=~\"$Namespace\",pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}\n"
    }
   ]
  },
  {
   "title": "Memory Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_heap_size{namespace=~\"$Namespace\",pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}\n"
    }
   ]
  },
  {
   "title": "Memory Physical Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (envoy_server_memory_physical_size{namespace=~\"$Namespace\",pod=~\"$pod\"})\n",
     "legendFormat": "{{pod}}\n"
    }
   ]
  },
  {
   "title": "HTTP Connection Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Connection Statistics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_total{\n            namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "HTTP Request Statistics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_rq_total{\n            namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "HTTP Connection Duration (p90)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  $quantiles,\n  sum by (pod, http_conn_manager_prefix, le) (\n    rate(\n      envoy_http_downstream_cx_length_ms_bucket{\n        namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n      }\n    [$__rate_interval])\n  )\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "HTTP Request Timing (p90)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  $quantiles,\n  sum by (pod, http_conn_manager_prefix, le) (\n    rate(\n      envoy_http_downstream_rq_time_bucket{\n        namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n      }\n    [$__rate_interval])\n  )\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "HTTP Request Reset Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_rq_rx_reset{\n            namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "HTTP Buffered Received Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    envoy_http_downstream_cx_rx_bytes_buffered{\n        namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n    }\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "Active HTTP Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    envoy_http_downstream_rq_active{\n        namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n    }\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "Active HTTP Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    envoy_http_downstream_cx_active{\n        namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n    }\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "HTTP Received Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_rx_bytes_total{\n            namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    },
    {
     "title": "HTTP Transmitted Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod, http_conn_manager_prefix) (\n    rate(\n        envoy_http_downstream_cx_tx_bytes_total{\n            namespace=~\"$Namespace\",pod=~\"$pod\",http_conn_manager_prefix=~\"$http_conn_manager_prefix\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{pod}} {{http_conn_manager_prefix}}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active clusters",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (pod, $clusterNameLabel) (\n    envoy_cluster_manager_active_clusters{\n        namespace=~\"$Namespace\",pod=~\"$pod\"\n    }\n)\n",
       "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
      }
     ]
    },
    {
     "title": "Total merged updates cancelled",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n    rate(\n        envoy_cluster_manager_update_merge_cancelled{\n            namespace=~\"$Namespace\",pod=~\"$pod\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{pod}}\n"
      }
     ]
    },
    {
     "title": "Total updates out of merge window",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum by (pod) (\n    rate(\n        envoy_cluster_manager_update_out_of_merge_window{\n            namespace=~\"$Namespace\",pod=~\"$pod\"\n        }\n    [$__rate_interval])\n)\n",
       "legendFormat": "{{pod}}\n"
      }
     ]
    }
   ]
  },
  { "title": "Cluster Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_total{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    envoy_cluster_upstream_rq_active{\n        namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n    }\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Pending total requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_pending_total{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Cancelled requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_cancelled{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Per try timeout requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_per_try_timeout{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Timeout requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_timeout{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Retry overflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_retry_overflow{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Retry requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_retry{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Retry backoff exponential",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_retry_backoff_exponential{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Retry limit exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_retry_limit_exceeded{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  },
  {
   "title": "Retry success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (pod, $clusterNameLabel) (\n    rate(\n        envoy_cluster_upstream_rq_retry_success{\n            namespace=~\"$Namespace\",pod=~\"$pod\", $clusterNameLabel=\"$cluster\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{pod}} {{$clusterNameLabel}}\n"
    }
   ]
  }
 ]
}