deploymentMode: SingleBinary

gateway:
  enabled: true
  hostNetwork: false # ← disable hostNetwork
  service:
    port: 3100

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage:
    type: "s3"
    bucketNames:
      chunks: group3-sre-logging
      ruler: group3-sre-logging
      admin: group3-sre-logging
    s3:
      region: ap-southeast-1
      s3ForcePathStyle: false

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/loki-s3-role

singleBinary:
  replicas: 1
  hostNetwork: false # ← also disable here
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraVolumes:
    - name: loki-data
      emptyDir: {}
  extraVolumeMounts:
    - name: loki-data
      mountPath: /var/loki

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false

lokiCanary:
  enabled: true
  interval: 10s
  lokiAddress: http://loki-gateway.logging.svc.cluster.local:3100/loki/api/v1/push
  labels:
    job: "loki-canary"
    service: "loki-canary"

# Extra manifests to deploy alongside Loki
extraObjects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: loki-metrics
      namespace: logging
      labels:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: single-binary
    spec:
      selector:
        app.kubernetes.io/name: loki
        app.kubernetes.io/component: single-binary
      ports:
        - name: http-metrics
          port: 3100
          targetPort: 3100

  - apiVersion: monitoring.coreos.com/v1
    kind: ServiceMonitor
    metadata:
      name: loki
      namespace: logging
      labels:
        release: kube-prometheus-stack
    spec:
      selector:
        matchLabels:
          app.kubernetes.io/name: loki
          app.kubernetes.io/component: single-binary
      namespaceSelector:
        matchNames:
          - logging
      endpoints:
        - port: http-metrics
          path: /metrics
          interval: 30s
