deploymentMode: SingleBinary

gateway:
  enabled: true
  hostNetwork: false # ← disable hostNetwork
  service:
    port: 3100

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: 2020-10-24
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: index_
          period: 24h
  storage:
    type: "s3"
    bucketNames:
      chunks: growfattest-logging
      ruler: growfattest-logging
      admin: growfattest-logging
    s3:
      region: ap-southeast-1
      s3ForcePathStyle: false

serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::255945442255:role/loki-s3-role

singleBinary:
  replicas: 1
  hostNetwork: false # ← also disable here
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  extraVolumes:
    - name: loki-data
      emptyDir: {}
  extraVolumeMounts:
    - name: loki-data
      mountPath: /var/loki

read:
  replicas: 0
write:
  replicas: 0
backend:
  replicas: 0

chunksCache:
  enabled: false
resultsCache:
  enabled: false

lokiCanary:
  enabled: true
  interval: 10s
  lokiAddress: http://loki-gateway.logging.svc.cluster.local:3100/loki/api/v1/push
  labels:
    job: "loki-canary"
    service: "loki-canary"
