config:
  lokiAddress: http://loki-gateway.logging.svc.cluster.local:3100/loki/api/v1/push

daemonset:
  enabled: true

tolerations:
  - effect: NoSchedule
    operator: Exists

client:
  timeout: 10s
