alertmanager:
  alertmanagerSpec:
    replicas: 2
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: group3-webhook
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
      - name: "null"
      - name: group3-webhook
        webhook_configs:
          - url: http://alertmanager-discord.kube-prometheus-stack:9094
            send_resolved: true

# Disable control plane alerts for EKS to reduce false positives.
# AWS manages the control plane components and doesn't expose their metrics endpoints to users.
defaultRules:
  rules:
    kubeControllerManager: false
    kubeScheduler: false

prometheus:
  prometheusSpec:
    additionalPrometheusRulesMap:
      custom-rules:
        groups:
          - name: node-efficiency
            rules:
              - alert: HostCpuIsUnderutilized
                expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) < 30
                for: 10m
                labels:
                  severity: info
                annotations:
                  summary: "Host CPU is underutilized (instance {{ $labels.instance }})"
                  description: "CPU usage has been < 30% for 10 minutes. Current usage: {{ printf \"%.1f\" $value }}%. Consider reducing instance size.\n  LABELS = {{ $labels }}"
