apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-node-efficiency-rules
  namespace: kube-prometheus-stack
  labels:
    app: kube-prometheus-stack
    release: kube-prometheus-stack
spec:
  groups:
    - name: node-efficiency
      rules:
        - alert: HostCpuIsUnderutilized
          expr: (100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) < 30
          for: 10m
          labels:
            severity: info
          annotations:
            summary: "Host CPU is underutilized (instance {{ $labels.instance }})"
            description: "CPU usage has been < 30% for 10 minutes. Current usage: {{ printf \"%.1f\" $value }}%. Consider reducing instance size.\n  LABELS = {{ $labels }}"