grafana:
  enabled: true
  service:
    type: LoadBalancer

  # Enable the dashboard sidecar
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folder: /var/lib/grafana/dashboards
      folderAnnotation: grafana_folder
      provider:
        name: "sidecarProvider"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        allowUiUpdates: true
        updateIntervalSeconds: 30
        options:
          path: /var/lib/grafana/dashboards
    datasources:
      enabled: true
      label: grafana_datasource
      labelValue: "1"
      searchNamespace: ALL
      initDatasources: true
