grafana:
  enabled: true
  defaultDatasourceEnabled: false # disable chart's default
  service:
    type: LoadBalancer

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki-gateway.logging.svc.cluster.local:3100
          uid: loki
          isDefault: false
          jsonData:
            httpHeaderName1: "X-Scope-OrgID"
          secureJsonData:
            httpHeaderValue1: "fake"

        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://prometheus-operated.kube-prometheus-stack.svc:9090
          uid: prometheus
          isDefault: true

  sidecar:
    dashboards:
      enabled: true
      folder: /var/lib/grafana/dashboards
      label: grafana_dashboard
      labelValue: "1"
    datasources:
      enabled: false # disable to avoid duplicate defaults

prometheus:
  prometheusSpec:
    livenessProbe:
      timeoutSeconds: 10
      periodSeconds: 30
    readinessProbe:
      timeoutSeconds: 10
      periodSeconds: 15
    startupProbe:
      timeoutSeconds: 10
      periodSeconds: 15
      failureThreshold: 60
