---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiSelectorTerms:
    - alias: bottlerocket@latest
  role: group3-SRE-KarpenterNodeRole
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: group3-SRE-cluster
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: group3-SRE-cluster
  tags:
    karpenter.sh/discovery: group3-SRE-cluster
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      requirements:
        - key: "karpenter.k8s.aws/instance-type"
          operator: In
          values: ["t3.medium"]
        - key: "karpenter.k8s.aws/instance-hypervisor"
          operator: In
          values: ["nitro"]
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
