apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: snakegame
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    generate_request_id: true
                    tracing:
                      operation_name: ingress
                    request_id_extension:
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
                        use_request_id_for_trace_sampling: true
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            - match:
                                path: "/healthz"
                              direct_response:
                                status: 200
                                body:
                                  inline_string: "OK"
                            - match:
                                prefix: "/"
                              route:
                                cluster: snake_service
                                timeout: 5s
                                retry_policy:
                                  retry_on: connect-failure,refused-stream,503
                                  num_retries: 3
                                  per_try_timeout: 2s
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: snake_service
          connect_timeout: 1s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          circuit_breakers:
            thresholds:
              - priority: DEFAULT
                max_connections: 100
                max_pending_requests: 100
                max_requests: 500
                max_retries: 3
          outlier_detection:
            consecutive_5xx: 3
            interval: 10s
            base_ejection_time: 30s
            max_ejection_percent: 50
          load_assignment:
            cluster_name: snake_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: snake-frontend-headless.snakegame.svc.cluster.local
                          port_value: 80
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
