apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: snakegame
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080   # Envoy listens on unprivileged port 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            # Static OK for AWS health checks
                            - match:
                                path: "/healthz"
                              direct_response:
                                status: 200
                                body:
                                  inline_string: "OK"
                            # All other requests to backend app
                            - match:
                                prefix: "/"
                              route:
                                cluster: snake_service
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: snake_service
          connect_timeout: 0.25s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          load_assignment:
            cluster_name: snake_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: snake-frontend-service.snakegame.svc.cluster.local
                          port_value: 80
    admin:
      access_log_path: "/dev/null"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
---
apiVersion: v1
kind: Service
metadata:
  name: snake-frontend-service
  namespace: snakegame
spec:
  type: LoadBalancer
  selector:
    app: snake-frontend
  ports:
    - name: http
      port: 80 # External LB port
      targetPort: 8080 # Envoy's internal listener port
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-metrics
  namespace: snakegame
  labels:
    app: snake-frontend
spec:
  selector:
    app: snake-frontend
  ports:
    - name: admin
      port: 9901
      targetPort: 9901
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-frontend
  namespace: snakegame
spec:
  replicas: 4
  selector:
    matchLabels:
      app: snake-frontend
  template:
    metadata:
      labels:
        app: snake-frontend
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.27.0
          args:
            - -c
            - /etc/envoy/envoy.yaml
            - --service-cluster
            - snake-frontend
          ports:
            - containerPort: 8080 # Handles inbound traffic
            - containerPort: 9901 # Prometheus metrics/admin
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
        - name: snake-frontend
          image: hannamatheos/snake-frontend:latest
          # No containerPort to avoid duplicate warnings
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-snake-monitor
  namespace: snakegame
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: snake-frontend
  namespaceSelector:
    matchNames:
      - snakegame
  endpoints:
    - port: admin
      path: /stats/prometheus
      interval: 15s
