apiVersion: v1
kind: ConfigMap
metadata:
  name: envoy-config
  namespace: snakegame
data:
  envoy.yaml: |
    static_resources:
      listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8080
          filter_chains:
            - filters:
                - name: envoy.filters.network.http_connection_manager
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                    stat_prefix: ingress_http
                    generate_request_id: true
                    request_id_extension:
                      typed_config:
                        "@type": type.googleapis.com/envoy.extensions.request_id.uuid.v3.UuidRequestIdConfig
                        use_request_id_for_trace_sampling: true
                    route_config:
                      name: local_route
                      virtual_hosts:
                        - name: backend
                          domains: ["*"]
                          routes:
                            - match:
                                path: "/healthz"
                              direct_response:
                                status: 200
                                body:
                                  inline_string: "OK"
                            - match:
                                prefix: "/"
                              route:
                                cluster: snake_service
                                timeout: 5s
                                retry_policy:
                                  retry_on: connect-failure,refused-stream,503
                                  num_retries: 3
                                  per_try_timeout: 2s
                    http_filters:
                      - name: envoy.filters.http.router
                        typed_config:
                          "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
        - name: snake_service
          connect_timeout: 1s
          type: STRICT_DNS
          lb_policy: ROUND_ROBIN
          circuit_breakers:
            thresholds:
              - priority: DEFAULT
                max_connections: 500
                max_pending_requests: 200
                max_requests: 1000
                max_retries: 5
          outlier_detection:
            consecutive_5xx: 3
            interval: 10s
            base_ejection_time: 30s
            max_ejection_percent: 50
          load_assignment:
            cluster_name: snake_service
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: snake-frontend-headless.snakegame.svc.cluster.local
                          port_value: 80
    admin:
      access_log:
        - name: envoy.access_loggers.stdout
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    overload_manager:
      refresh_interval: 0.25s
      resource_monitors:
        - name: "envoy.resource_monitors.fixed_heap"
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.resource_monitors.fixed_heap.v3.FixedHeapConfig
            max_heap_size_bytes: 2147483648
      actions:
        - name: "envoy.overload_actions.stop_accepting_requests"
          triggers:
            - name: "envoy.resource_monitors.fixed_heap"
              threshold:
                value: 0.95
---
apiVersion: v1
kind: Service
metadata:
  name: snake-frontend-service
  namespace: snakegame
spec:
  type: LoadBalancer
  selector:
    app: snake-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: snake-frontend-headless
  namespace: snakegame
spec:
  clusterIP: None
  selector:
    app: snake-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-metrics
  namespace: snakegame
  labels:
    app: snake-frontend
spec:
  selector:
    app: snake-frontend
  ports:
    - name: admin
      port: 9901
      targetPort: 9901
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: snake-frontend
  namespace: snakegame
spec:
  replicas: 4
  selector:
    matchLabels:
      app: snake-frontend
  template:
    metadata:
      labels:
        app: snake-frontend
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.27.0
          args:
            - -c
            - /etc/envoy/envoy.yaml
            - --service-cluster
            - snake-frontend
          ports:
            - containerPort: 8080
            - containerPort: 9901
          startupProbe:
            httpGet:
              path: /ready
              port: 9901
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /ready
              port: 9901
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
        - name: snake-frontend
          image: hannamatheos/snake-frontend:latest
          ports:
            - containerPort: 80
          # Readiness probe removed to avoid 404 failures
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-snake-monitor
  namespace: snakegame
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: snake-frontend
  namespaceSelector:
    matchNames:
      - snakegame
  endpoints:
    - port: admin
      path: /stats/prometheus
      interval: 15s
