name: Deploy Infrastructure
run-name: Deploying infrastructure by ${{ github.actor }}

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    uses: ./.github/workflows/testoidc.yaml
    secrets: inherit

  setup:
    needs: terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ap-southeast-1

      - name: Make setup.sh executable and run
        run: |
          chmod +x setup.sh
          ./setup.sh