name: Deploy Helm
run-name: Deploying Helm by ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      refToBuild:
        description: "Branch, tag or commit SHA to build"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.refToBuild }}

      - name: Build
        run: echo "Running from commit ${{ inputs.refToBuild }}"

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ap-southeast-1

      - name: List files
        run: ls -R

      - name: Make setup.sh executable and run
        run: |
          chmod +x setup.sh
          ./setup.sh
