name: Project setup Private access
run-name: Running Terraform Checks by ${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  Initial-Checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Getting initiator name
        run: echo "Workflow initiated by ${{ github.actor }} from branch ${{ github.ref_name }}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_mem1: ${{ secrets.MEM1 }}
          TF_VAR_mem2: ${{ secrets.MEM2 }}
          TF_VAR_mem3: ${{ secrets.MEM3 }}
          TF_VAR_mem4: ${{ secrets.MEM4 }}
          TF_VAR_mem5: ${{ secrets.MEM5 }}

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply --auto-approve
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_mem1: ${{ secrets.MEM1 }}
          TF_VAR_mem2: ${{ secrets.MEM2 }}
          TF_VAR_mem3: ${{ secrets.MEM3 }}
          TF_VAR_mem4: ${{ secrets.MEM4 }}
          TF_VAR_mem5: ${{ secrets.MEM5 }}
