name: OIDC Terraform teardown
run-name: Running Terraform teardown by ${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ap-southeast-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7 # or your preferred version

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Make detach.sh executable and run #force detach existing resources before teardown
        run: |
          chmod +x detach.sh
          ./detach.sh

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy --auto-approve
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_team_members: '["${{ secrets.MEM1 }}","${{ secrets.MEM2 }}","${{ secrets.MEM3 }}","${{ secrets.MEM4 }}","${{ secrets.MEM5 }}"]'
