name: OIDC Project setup
run-name: Running Terraform Checks by ${{ github.actor }}

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      aws_account_id:
        required: true
        type: string
      team_members:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    outputs:
      cluster_name: ${{ steps.set-cluster-name.outputs.cluster_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ap-southeast-1

      - name: Debug OIDC Token
        run: 'echo "Assumed AWS Account ID: ${{ steps.configure-aws-credentials.outputs.aws-account-id }}"'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Debug Terraform Vars
        run: |
          echo "Account ID: $TF_VAR_aws_account_id"
          echo "Team Members: $TF_VAR_team_members"
        env:
          TF_VAR_aws_account_id: ${{ inputs.aws_account_id }}
          TF_VAR_team_members: ${{ inputs.team_members }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply --auto-approve
        env:
          TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
          TF_VAR_team_members: '["${{ secrets.MEM1 }}","${{ secrets.MEM2 }}","${{ secrets.MEM3 }}","${{ secrets.MEM4 }}","${{ secrets.MEM5 }}"]'

      - name: Set cluster name output
        id: set-cluster-name
        run: echo "cluster_name=growfattest-cluster" >> $GITHUB_OUTPUT
